/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.81
 * Generated at: 2018-03-06 12:57:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.DadosUsuario;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import javax.persistence.Query;
import javax.persistence.EntityManager;
import br.com.cifpag.uteis.ConexaoEntityFactory;
import java.util.List;
import br.com.cifpag.daoGenericos.UsuarioDaoImplementacao;
import br.com.cifpag.daoGenericos.UsuarioDao;
import br.com.cifpag.entity.Usuario;
import br.com.cifpag.daoGenericos.DadosUsuarioImplementacao;
import br.com.cifpag.daoGenericos.DadosUsuarioDao;
import br.com.cifpag.entity.DadosUsuario;

public final class PerfilUsuario_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/tags/master.tag", Long.valueOf(1520281399000L));
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

DadosUsuario dadosUsuario = new DadosUsuario();
Usuario usuario = new Usuario();

try{
	EntityManager emUsuario = new ConexaoEntityFactory().getEntityManager();
	Query queryUsuario = (Query) emUsuario.createNativeQuery("SELECT usua_id FROM controle_acesso.usuario WHERE usua_usuario = " + "'"+request.getSession().getAttribute("usuarioLogado")+"'");
	Object objUsuario = queryUsuario.getSingleResult();

	UsuarioDao usuarioDao = new UsuarioDaoImplementacao();
	usuario = usuarioDao.getById(Usuario.class, Integer.parseInt(objUsuario.toString()));
	
	
	EntityManager em = new ConexaoEntityFactory().getEntityManager();
	Query query = (Query) em.createNativeQuery("SELECT clie_id FROM sistema.dados_usuario INNER JOIN controle_acesso.usuario ON usua_id = clie_usuario WHERE usua_usuario = " + "'"+request.getSession().getAttribute("usuarioLogado")+"'");
	Object obj = query.getSingleResult();

	DadosUsuarioDao usuarioDAO = new DadosUsuarioImplementacao();
	dadosUsuario = usuarioDAO.getById(DadosUsuario.class, Integer.parseInt(obj.toString()));

}catch(Exception ex){
	System.out.println("ERROR: " + ex);
}

      out.write('\n');
      out.write('\n');
      //  c:set
      org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
      boolean _jspx_th_c_005fset_005f0_reused = false;
      try {
        _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fset_005f0.setParent(null);
        // /WEB-INF/views/DadosUsuario/PerfilUsuario.jsp(43,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fset_005f0.setVar("bodyContent");
        int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
        if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005fset_005f0);
          }
          do {
            out.write("\n");
            out.write("\t<div class=\"row\">\n");
            out.write("\t\t<div class=\"col-md-12\">\n");
            out.write("\t\t\t<div class=\"portlet light bordered\">\n");
            out.write("\t\t\t\t<div class=\"portlet-title\">\n");
            out.write("\t\t\t\t\t");

						try {
					
            out.write("\n");
            out.write("\t\t\t\t\t");

						if (request.getParameter("mensagem").equals("falha")) {
					
            out.write("\n");
            out.write("\t\t\t\t\t<div style=\"width: 100%\" class=\"alert alert-danger \">\n");
            out.write("\t\t\t\t\t\t<button class=\"close\" data-close=\"alert\"></button>\n");
            out.write("\t\t\t\t\t\tErro ao efetuar operação!\n");
            out.write("\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t");

						}
								if (request.getParameter("mensagem").equals("sucesso")) {
					
            out.write("\n");
            out.write("\t\t\t\t\t<div style=\"width: 100%\" class=\"alert alert-success \">\n");
            out.write("\t\t\t\t\t\t<button class=\"close\" data-close=\"alert\"></button>\n");
            out.write("\t\t\t\t\t\tSucesso ao efetuar operação!\n");
            out.write("\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t");

						}
					
            out.write("\n");
            out.write("\t\t\t\t\t");

						} catch (NullPointerException ex) {
							}
					
            out.write("\n");
            out.write("\t\t\t\t</div>\n");
            out.write("\n");
            out.write("\t\t\t\t<div class=\"profile-sidebar\">\n");
            out.write("\t\t\t\t\n");
            out.write("\t\t\t\t\t<div class=\"portlet light profile-sidebar-portlet\">\n");
            out.write("\t\t\t\t\t\t<div class=\"\">\n");
            out.write("\t\t\t\t\t\t\t<img id=\"perfilImg\" src=\"/CifPag/assets/layouts/layout/img/avatar3_small.jpg\" class=\"img-responsive\" alt=\"\">\n");
            out.write("\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t<div class=\"profile-usertitle\">\n");
            out.write("\t\t\t\t\t\t\t<div class=\"profile-usertitle-name\">Nome Usuario</div>\n");
            out.write("\t\t\t\t\t\t\t<div class=\"profile-usertitle-job\">Email</div>\n");
            out.write("\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\n");
            out.write("\t\t\t\t\t<div class=\"portlet light\">\n");
            out.write("\t\t\t\t\t\t<div class=\"row list-separated profile-stat\">\n");
            out.write("\t\t\t\t\t\t\t<div class=\"col-md-6 col-sm-6 col-xs-6\">\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"uppercase profile-stat-title\">0</div>\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"uppercase profile-stat-text\">Faturas Pendetes</div>\n");
            out.write("\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t<div class=\"col-md-6 col-sm-6 col-xs-6\">\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"uppercase profile-stat-title\">0</div>\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"uppercase profile-stat-text\">Faturas Pagas</div>\n");
            out.write("\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t</div>\n");
            out.write("\n");
            out.write("\t\t\t\t<div class=\"profile-content\">\n");
            out.write("\t\t\t\t\t<div class=\"row\">\n");
            out.write("\t\t\t\t\t\t<div class=\"col-md-12\">\n");
            out.write("\t\t\t\t\t\t\t<div class=\"portlet light \">\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"portlet-title tabbable-line\">\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"caption caption-md\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<i class=\"icon-globe theme-font hide\"></i> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t<span class=\"caption-subject font-blue-madison bold uppercase\">Perfil</span>\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t<ul class=\"nav nav-tabs\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<li class=\"active\"><a data-target=\"#tab_1_1\" data-toggle=\"tab\">Dados pessoais</a></li>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<li><a data-target=\"#tab_1_2\" data-toggle=\"tab\">Troque sua foto</a></li>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<li><a data-target=\"#tab_1_3\" data-toggle=\"tab\">Troque sua senha</a></li>\n");
            out.write("\t\t\t\t\t\t\t\t\t</ul>\n");
            out.write("\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t<div class=\"portlet-body\">\n");
            out.write("\t\t\t\t\t\t\t\t\t<div class=\"tab-content\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tab-pane active\" id=\"tab_1_1\" >\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<form role=\"form\" action=\"/CifPag/DadosUsuario/SalvarDadosPessoais\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<input style=\"display: none\" name=\"clieId\" id=\"clieId\" value=\"");
out.print(dadosUsuario.getClieId()); 
            out.write("\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Nome Completo</label> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa\"></i> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" required value=\"");
out.print(dadosUsuario.getClieNome()); 
            out.write("\" name=\"clieNome\" />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Data Nascimento</label> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa\"></i> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" required value=\"");
out.print(dadosUsuario.getClieDataNascimento()); 
            out.write("\" name=\"clieDataNascimento\" />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label for=\"single\" class=\"control-label\">Selecione o tipo de pessoa</label>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-icon right\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<select id=\"singleAlter\" class=\"form-control select2\" name=\"clieTipoPessoa\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
 	
																	EntityManager emTipoPessoa = new ConexaoEntityFactory().getEntityManager();
																	Query tipoPessoa = (Query) emTipoPessoa.createNativeQuery("SELECT tipo_id FROM sistema.tipo_pessoa WHERE tipo_id = " + dadosUsuario.getClieTipoPessoa());
																	Object tipoTipoPessoa = tipoPessoa.getSingleResult();
																	
																	Query queryListaTipoPessoa = (Query) emTipoPessoa.createNativeQuery("SELECT tipo_id, tipo_tipo_pessoa FROM sistema.tipo_pessoa WHERE tipo_id = " + tipoTipoPessoa);
																	List<Object[]> listTipoPessoa = queryListaTipoPessoa.getResultList();
																	for (Object[] obj : listTipoPessoa) { 
																
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
out.print(obj[0]);
            out.write('"');
            out.write('>');
out.print(obj[1]);
            out.write("</option>\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");

																	Query todasPessoas = (Query) emTipoPessoa.createNativeQuery("SELECT tipo_id, tipo_tipo_pessoa FROM sistema.tipo_pessoa WHERE tipo_id != " + tipoTipoPessoa);
																	List<Object[]> listTipos = todasPessoas.getResultList();
																	for (Object[] objTipoPessoa : listTipos) {
																
            out.write("\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<option value=\"");
out.print(objTipoPessoa[0]);
            out.write('"');
            out.write('>');
out.print(objTipoPessoa[1]);
            out.write("</option>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
			
																	}
																
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t");

																	}
																
            out.write("\t\n");
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</select>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">RG</label> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa\"></i> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" required value=\"");
out.print(dadosUsuario.getClieRg()); 
            out.write("\" name=\"clieRg\" />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">CPF</label> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa\"></i> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
out.print(dadosUsuario.getClieCpf()); 
            out.write("\" name=\"clieCpf\" />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">CNPJ</label> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa\"></i> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" value=\"");
out.print(dadosUsuario.getClieCnpj()); 
            out.write("\" name=\"clieCnpj\" />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Nome Fantasia</label> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa\"></i> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" required value=\"");
out.print(dadosUsuario.getClieNomeFantasia()); 
            out.write("\" name=\"clieNomeFantasia\" />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Telefone celular</label> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa\"></i> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" required value=\"");
out.print(dadosUsuario.getClieCelular()); 
            out.write("\" name=\"clieCelular\" />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Telefone fixo</label> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa\"></i> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"text\" class=\"form-control\" required value=\"");
out.print(dadosUsuario.getClieTelefone()); 
            out.write("\" name=\"clieTelefone\" />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input style=\"display: none\" type=\"text\" class=\"form-control\" required value=\"");
out.print(dadosUsuario.getClieEndereco()); 
            out.write("\" name=\"clieEndereco\" />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Endereco\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"required\"></span>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</label>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"input-icon right\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");

												EntityManager emIdEndereco = new ConexaoEntityFactory().getEntityManager();
												Query queryIdEndereco = (Query) emIdEndereco.createNativeQuery("SELECT ende_id FROM sistema.endereco INNER JOIN sistema.dados_usuario ON ende_id = clie_endereco WHERE clie_id = " + dadosUsuario.getClieId());
												Object objIdEndereco = queryIdEndereco.getSingleResult();
												
            out.write("\n");
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
 	
												
													EntityManager em = new ConexaoEntityFactory().getEntityManager();
													Query query = (Query) em.createNativeQuery("SELECT ende_endereco, ende_bairro, cida_cidade, clie_endereco FROM sistema.dados_usuario INNER JOIN sistema.endereco ON ende_id = clie_endereco INNER JOIN sistema.cidade ON cida_id = ende_cidade WHERE ende_id = " + objIdEndereco);
													List<Object[]> list = query.getResultList();
													for (Object[] obj : list) { 
												
            out.write("\n");
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa\"></i> <input readonly=\"true\" type=\"text\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
out.print(obj[0]);
            out.write("\" class=\"form-control\" /> <br />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa\"></i> <input readonly=\"true\" type=\"text\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
out.print(obj[1]);
            out.write("\" class=\"form-control\" /> <br />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa\"></i> <input readonly=\"true\" type=\"text\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tvalue=\"");
out.print(obj[2]);
            out.write("\" class=\"form-control\" /> <br>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t");
 } 
            out.write("\n");
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"btn-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"/CifPag/Endereco/EditarPeloDadosUsuario?id=");
out.print(dadosUsuario.getClieEndereco()); 
            out.write("\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tid=\"sample_editable_1_new\" class=\"btn sbold green\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tEditar Endereco <i class=\"fa fa-plus\"></i>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</a>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"help-block with-errors\"></div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"margiv-top-10\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button ng-click=\"AlterarDados()\" type=\"submit\" class=\"btn green\">Alterar</button>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"btn default\">Cancelar </a>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tab-pane\" id=\"tab_1_2\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<p>Selecione sua foto.</p>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<form role=\"form\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"fileinput fileinput-new\" data-provides=\"fileinput\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"fileinput-new thumbnail\" style=\"width: 200px; height: 150px;\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<img id=\"img\" src=\"\" alt=\"\" />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<input ng-show=\"campo\" ng-model=\"caminhoImagem\" id=\"caminho\" type=\"text\" class=\"form-control\" />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<span class=\"btn default btn-file\"> <span\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fileinput-new\"> Selecione a imagem </span> <span\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"fileinput-exists\"> Change </span> <input\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tonchange=\"angular.element(this).scope().uploadFile(this.files)\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\ttype=\"file\" name=\"files[]\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t</span> <a href=\"javascript:;\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tclass=\"btn default fileinput-exists\"\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t\tdata-dismiss=\"fileinput\"> Remove </a>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"fileinput-preview fileinput-exists thumbnail\" style=\"max-width: 200px; max-height: 150px;\"></div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"margin-top-10\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button ng-click=\"TrocarFoto()\" type=\"submit\" class=\"btn green\">Alterar</button>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<a href=\"javascript:;\" class=\"btn default\"> Cancelar </a>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t<div class=\"tab-pane\" id=\"tab_1_3\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t<form role=\"form\" action=\"/CifPag/Usuario/SalvarPerfil\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input style=\"display: none\" type=\"text\" class=\"form-control\" value=\"");
out.print(usuario.getUsuaId());
            out.write("\" name=\"usuaId\" />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<input style=\"display: none\" type=\"text\" id=\"usuaUsuario\" value=\"");
out.print(usuario.getUsuaUsuario()); 
            out.write("\" class=\"form-control\" required name=\"usuaUsuario\" />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Nova senha</label> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa\"></i> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" id=\"senha\" value=\"");
out.print(usuario.getUsuaSenha()); 
            out.write("\" class=\"form-control\" required name=\"usuaSenha\" />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"form-group\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<label class=\"control-label\">Repita a senha</label> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<i class=\"fa\"></i> \n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<input type=\"password\" equalTo=\"#senha\" value=\"");
out.print(usuario.getUsuaSenha()); 
            out.write("\" class=\"form-control\" required />\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"help-block with-errors\"></div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t<div class=\"\">\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t\t<button type=\"submit\" class=\"btn green\">Alterar</button>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t\t</form>\n");
            out.write("\t\t\t\t\t\t\t\t\t\t</div>\t\n");
            out.write("\t\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t\t</div>\n");
            out.write("\t\t\t\t</div>\n");
            out.write("\t\t\t</div>\n");
            out.write("\t\t</div>\n");
            out.write("\t</div>\n");
            int evalDoAfterBody = _jspx_th_c_005fset_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_c_005fset_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.reuse(_jspx_th_c_005fset_005f0);
        _jspx_th_c_005fset_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
      }
      out.write('\n');
      out.write('\n');
      if (_jspx_meth_t_005fmaster_005f0(_jspx_page_context))
        return;
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_t_005fmaster_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  t:master
    org.apache.jsp.tag.web.master_tag _jspx_th_t_005fmaster_005f0 = new org.apache.jsp.tag.web.master_tag();
    _jsp_getInstanceManager().newInstance(_jspx_th_t_005fmaster_005f0);
    try {
      _jspx_th_t_005fmaster_005f0.setJspContext(_jspx_page_context);
      javax.servlet.jsp.tagext.JspFragment _jspx_temp0 = new Helper( 0, _jspx_page_context, _jspx_th_t_005fmaster_005f0, null);
      // /WEB-INF/views/DadosUsuario/PerfilUsuario.jsp(336,0) null
      _jspx_th_t_005fmaster_005f0.setScripts_css(_jspx_temp0);
      javax.servlet.jsp.tagext.JspFragment _jspx_temp1 = new Helper( 1, _jspx_page_context, _jspx_th_t_005fmaster_005f0, null);
      // /WEB-INF/views/DadosUsuario/PerfilUsuario.jsp(336,0) null
      _jspx_th_t_005fmaster_005f0.setScripts_js_page_level_plugins(_jspx_temp1);
      javax.servlet.jsp.tagext.JspFragment _jspx_temp2 = new Helper( 2, _jspx_page_context, _jspx_th_t_005fmaster_005f0, null);
      // /WEB-INF/views/DadosUsuario/PerfilUsuario.jsp(336,0) null
      _jspx_th_t_005fmaster_005f0.setScripts_js_page_level_scripts(_jspx_temp2);
      _jspx_th_t_005fmaster_005f0.setJspBody(new Helper( 3, _jspx_page_context, _jspx_th_t_005fmaster_005f0, null));
      _jspx_th_t_005fmaster_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_t_005fmaster_005f0);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public boolean invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("<link href=\"/CifPag/assets/global/plugins/datatables/datatables.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"/CifPag/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("        <link href=\"/CifPag/assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css\" rel=\"stylesheet\" type=\"text/css\" /> \n");
      out.write("        <link href=\"http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\t\t<link href=\"/CifPag/assets/global/plugins/font-awesome/css/font-awesome.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\t\t<link href=\"/CifPag/assets/global/plugins/simple-line-icons/simple-line-icons.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\t\t<link href=\"/CifPag/assets/global/plugins/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\t\t<link href=\"/CifPag/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\t\t<link href=\"/CifPag/assets/global/plugins/bootstrap-fileinput/bootstrap-fileinput.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\t\t<link href=\"/CifPag/assets/global/css/components.min.css\" rel=\"stylesheet\" id=\"style_components\" type=\"text/css\" />\n");
      out.write("\t\t<link href=\"/CifPag/assets/global/css/plugins.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\t\t<link href=\"/CifPag/assets/pages/css/profile.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\t\t<link href=\"/CifPag/assets/layouts/layout/css/layout.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\t\t<link href=\"/CifPag/assets/layouts/layout/css/themes/darkblue.min.css\" rel=\"stylesheet\" type=\"text/css\" id=\"style_color\" />\n");
      out.write("\t\t<link href=\"/CifPag/assets/layouts/layout/css/custom.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\t\t<link href=\"/CifPag/assets/global/plugins/select2/css/select2.min.css\" rel=\"stylesheet\" type=\"text/css\" />\n");
      out.write("\t\t<link href=\"/CifPag/assets/global/plugins/select2/css/select2-bootstrap.min.css\" rel=\"stylesheet\" type=\"text/css\" />");
      return false;
    }
    public boolean invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("<script src=\"/CifPag/assets/global/scripts/datatable.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"/CifPag/assets/global/plugins/datatables/datatables.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"/CifPag/assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"/CifPag/assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js\" type=\"text/javascript\"></script>\n");
      out.write("        <script src=\"/CifPag/assets/global/plugins/select2/js/select2.full.min.js\" type=\"text/javascript\"></script>\n");
      out.write("\t\t<script src=\"/CifPag/assets/pages/scripts/components-select2.min.js\"type=\"text/javascript\"></script>\n");
      out.write("\t\t<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery.mask/1.14.11/jquery.mask.min.js\"></script> \n");
      out.write("\t\t<script src=\"/CifPag/assets/global/plugins/jquery-validation/js/jquery.validate.min.js\" type=\"text/javascript\"></script>");
      return false;
    }
    public boolean invoke2( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("<script>\n");
      out.write("\t\t\t$(document).ready(function(){\t\n");
      out.write("\t\t\t\t$(\"#single\").select2();\t\n");
      out.write("\t\t\t\t$(\"#singleAlter\").select2();\t\n");
      out.write("\t\t\t});\n");
      out.write("\t\t</script>\n");
      out.write("\n");
      out.write("\t\t<script src=\"/CifPag/assets/pages/scripts/table-datatables-buttons.min.js\" type=\"text/javascript\"></script>\t\n");
      out.write("\t\t<script src=\"/CifPag/assets/pages/scripts/form-validation.min.js\" type=\"text/javascript\"></script>");
      return false;
    }
    public boolean invoke3( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write('\n');
      out.write('	');
      out.write('	');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${bodyContent}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("    \n");
      out.write("\t");
      return false;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
          case 2:
            invoke2( out );
            break;
          case 3:
            invoke3( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
